CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Authors" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    CONSTRAINT "PK_Authors" PRIMARY KEY ("Id")
);

CREATE TABLE "Books" (
    "BookId" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" text NOT NULL,
    "PublishDate" timestamp with time zone NOT NULL,
    "BasePrice" numeric NOT NULL,
    "AuthorId" integer NOT NULL,
    CONSTRAINT "PK_Books" PRIMARY KEY ("BookId"),
    CONSTRAINT "FK_Books_Authors_AuthorId" FOREIGN KEY ("AuthorId") REFERENCES "Authors" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Books_AuthorId" ON "Books" ("AuthorId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260417065702_IntitalMigration', '8.0.26');

COMMIT;

START TRANSACTION;

INSERT INTO "Authors" ("Id", "FirstName", "LastName")
VALUES (1, 'Frank', 'Herbert');
INSERT INTO "Authors" ("Id", "FirstName", "LastName")
VALUES (2, 'George', 'Orwell');
INSERT INTO "Authors" ("Id", "FirstName", "LastName")
VALUES (3, 'Julie', 'Lerman');
INSERT INTO "Authors" ("Id", "FirstName", "LastName")
VALUES (4, 'Julia', 'Lerman');
INSERT INTO "Authors" ("Id", "FirstName", "LastName")
VALUES (5, 'Deepak', 'Koshy');
INSERT INTO "Authors" ("Id", "FirstName", "LastName")
VALUES (6, 'Bini', 'Koshy');
INSERT INTO "Authors" ("Id", "FirstName", "LastName")
VALUES (7, 'Thomas', 'Koshy');

SELECT setval(
    pg_get_serial_sequence('"Authors"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Authors") + 1,
        nextval(pg_get_serial_sequence('"Authors"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260417075926_SeedAuthorDetails', '8.0.26');

COMMIT;

